data.path.training-type: data/load/csv/training-type.csv
data.path.user: data/load/csv/user.csv
data.path.trainee: data/load/json/trainee.json
#data.path.trainer: data/trainer.csv
#data.path.training: data/training.csv

data.save.users: data/save/users.json
data.save.trainees: data/save/trainees.json
data.save.trainers: data/save/trainers.json
data.save.trainings: data/save/trainings.json
data.save.training-types: data/save/training-types.json
