datasource.url: jdbc:postgresql://localhost:5432/gym
datasource.username: postgres
datasource.password: postgres
datasource.pool-size: 10
datasource.master-change-log: db/changelog/master.yaml

#  jpa:
#    properties.hibernate:
#      format_sql: true
